// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Persistance.Migrations
{
    [DbContext(typeof(FinanceDataBaseContext))]
    [Migration("20240403202349_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Finance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Createrd")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinanceType")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyStatementId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MonthlyStatementId");

                    b.ToTable("Finances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = -100.00m,
                            Createrd = new DateTime(2024, 4, 3, 22, 23, 48, 500, DateTimeKind.Local).AddTicks(5292),
                            FinanceType = 2,
                            Title = "Biedronka"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1000.00m,
                            Createrd = new DateTime(2024, 4, 3, 20, 23, 48, 500, DateTimeKind.Utc).AddTicks(5296),
                            FinanceType = 1,
                            Title = "Wypłata"
                        });
                });

            modelBuilder.Entity("Domain.Models.MonthlyStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createrd")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MonthlyStatements");
                });

            modelBuilder.Entity("Domain.Models.Finance", b =>
                {
                    b.HasOne("Domain.Models.MonthlyStatement", null)
                        .WithMany("MonthBalance")
                        .HasForeignKey("MonthlyStatementId");
                });

            modelBuilder.Entity("Domain.Models.MonthlyStatement", b =>
                {
                    b.Navigation("MonthBalance");
                });
#pragma warning restore 612, 618
        }
    }
}
