FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

COPY . ./

RUN dotnet restore ./src/BackEnd/FinToUp.sln

RUN dotnet build ./src/BackEnd/FinToUp.sln --configuration Release --output /app/output
