@host = http://localhost
@port = 5000
@API_HostAddress = {{host}}:{{port}}



###
# Get all finances
Get {{API_HostAddress}}/api/finances



###
# Get finance by id 
Get {{API_HostAddress}}/api/finances/12



###
# Create New finance
POST {{API_HostAddress}}/api/finances
Content-Type: application/json

{
  "title": "Nowy Tytuł",
  "amount": 510.00,
  "financeType": 1
}


###
# Update finance
PUT {{API_HostAddress}}/api/finances
Content-Type: application/json

{
  "id": 1,
  "title": "Zaktualizowany Tytuł",
  "amount": 520.00,
  "financeType": 2
}



###
# Delete finance by id 
DELETE {{API_HostAddress}}/api/finances/1
