name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - 'Sprints/*'

jobs:
  Build_Backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Publish Docker Image
        run: |
          docker build -t myapp-build -f ./src/BackEnd/Dockerfile.build .
          docker create --name myapp-container myapp-build
          docker cp myapp-container:/app/output ./output
          docker rm myapp-container

  Test_Backend:
    needs: Build_Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy Built Artifacts
        run: |
          mkdir -p ./src/BackEnd/
          cp -r ./output/* ./src/BackEnd/

      - name: Build and Test Docker Image
        run: |
          docker build -t myapp-test -f ./src/Test/Dockerfile.test .
