name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'sprints/*'

jobs:
  Build_Backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .Net Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./src/BackEnd/FinToUp.sln

      - name: Build .Net Core
        run: dotnet build ./src/BackEnd/FinToUp.sln --no-restore --configuration Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-app
          path: ./src/BackEnd/FinToUp/bin/Release/net8.0/

  Test_Backend:
    needs: Build_Backend
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: built-app
          path: ./src/BackEnd/FinToUp/bin/Release/net8.0/

      - name: Setup .Net Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Test Project
        run: dotnet test ./src/Test/Test.csproj --no-build --no-restore
