name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'sprints/*'

jobs:
  Build_Backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/BackEnd/FinToUp.sln

      - name: Build the project
        run: dotnet build ./src/BackEnd/FinToUp.sln --configuration Release

      - name: Upload built application as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-app
          path: ./src/BackEnd/FinToUp/bin/Release/

  Test_Backend:
    needs: Build_Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download built application artifact
        uses: actions/download-artifact@v4
        with:
          name: built-app
          path: ./src/BackEnd/FinToUp/bin/Release/

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run tests
        run: dotnet test ./src/Test/Test.csproj --no-build --no-restore
