name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'sprints/*'
  pull_request:
    branches:
      - main
      - 'sprints/*'

jobs:
  Build_Backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/BackEnd/FinToUp.sln

      - name: Build the project
        run: dotnet build ./src/BackEnd/FinToUp.sln --configuration Release

      - name: Cache built application
        uses: actions/cache@v3
        with:
          path: ./src/BackEnd/
          key: ${{ runner.os }}-built-app-${{ github.sha }}

  Test_Backend:
    needs: Build_Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: ./src/BackEnd/
          key: ${{ runner.os }}-built-app-${{ github.sha }}

      - name: Run tests
        run: dotnet test ./src/Test/Test.csproj